name: Actions 😎

on: [push, pull_request]

jobs:

  check_licence:
    name: Check Unity license
    runs-on: ubuntu-latest
    steps:
      - name: Check Unity license
        if: ${{secrets.UsNITY_LICENSE == '' || secrets.UNITY_EMAIL == '' || secrets.UNITY_PASSWORD == ''}}
        run: |
           echo "No Unity Licese found!"
           exit 1
        

  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project for WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
      # build for windows   
      - name: Build project for windows
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
  
      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
